[workspace]
resolver = "2"
members = [
    "crates/roc_host",
    "crates/roc_host_lib",
    "crates/roc_host_bin",
    "crates/roc_std",
]

[profile.release]
lto = true
strip = "debuginfo"
codegen-units = 1
