[workspace]
resolver = "2"
members = [
    "crates/roc_std",
    "crates/roc_host",
    "crates/roc_host_lib",
    "crates/roc_host_bin",
]

[profile.release]
lto = true
strip = "debuginfo"
# Enabling this triggered a segmentation fault (see issue github.com/roc-lang/roc/issues/6121).
# That issue is notoriously fickle, so disableing this may just happen to shuffle the code enough to avoid it.
# codegen-units = 1
