// ⚠️ GENERATED CODE ⚠️ - this entire file was generated by the `roc glue` CLI command

#![allow(unused_unsafe)]
#![allow(dead_code)]
#![allow(unused_mut)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(clippy::undocumented_unsafe_blocks)]
#![allow(clippy::redundant_static_lifetimes)]
#![allow(clippy::unused_unit)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::let_and_return)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::needless_borrow)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::non_canonical_partial_ord_impl)]

use roc_std::roc_refcounted_noop_impl;
use roc_std::RocRefcounted;

#[derive(Clone, Copy, PartialEq, PartialOrd, Eq, Ord, Hash)]
#[repr(u8)]
pub enum HappyPayloadlessTag {
    Bar = 0,
    Baz = 1,
    Foo = 2,
}

impl core::fmt::Debug for HappyPayloadlessTag {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Bar => f.write_str("HappyPayloadlessTag::Bar"),
            Self::Baz => f.write_str("HappyPayloadlessTag::Baz"),
            Self::Foo => f.write_str("HappyPayloadlessTag::Foo"),
        }
    }
}

roc_refcounted_noop_impl!(HappyPayloadlessTag);

#[derive(Clone, Copy, PartialEq, PartialOrd, Eq, Ord, Hash)]
#[repr(u8)]
pub enum discriminant_SadPayloadfulTag {
    Bar = 0,
    Baz = 1,
    Foo = 2,
}

impl core::fmt::Debug for discriminant_SadPayloadfulTag {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Bar => f.write_str("discriminant_SadPayloadfulTag::Bar"),
            Self::Baz => f.write_str("discriminant_SadPayloadfulTag::Baz"),
            Self::Foo => f.write_str("discriminant_SadPayloadfulTag::Foo"),
        }
    }
}

roc_refcounted_noop_impl!(discriminant_SadPayloadfulTag);

#[derive(Clone, Copy)]
#[repr(C, align(1))]
pub union union_SadPayloadfulTag {
    Bar: (),
    Baz: (),
    Foo: u8,
}

// TODO(@roc-lang): See https://github.com/roc-lang/roc/issues/6012
// const _SIZE_CHECK_union_SadPayloadfulTag: () = assert!(core::mem::size_of::<union_SadPayloadfulTag>() == 1);
const _ALIGN_CHECK_union_SadPayloadfulTag: () =
    assert!(core::mem::align_of::<union_SadPayloadfulTag>() == 1);

const _SIZE_CHECK_SadPayloadfulTag: () = assert!(core::mem::size_of::<SadPayloadfulTag>() == 2);
const _ALIGN_CHECK_SadPayloadfulTag: () = assert!(core::mem::align_of::<SadPayloadfulTag>() == 1);

impl SadPayloadfulTag {
    /// Returns which variant this tag union holds. Note that this never includes a payload!
    pub fn discriminant(&self) -> discriminant_SadPayloadfulTag {
        unsafe {
            let bytes = core::mem::transmute::<&Self, &[u8; core::mem::size_of::<Self>()]>(self);

            core::mem::transmute::<u8, discriminant_SadPayloadfulTag>(*bytes.as_ptr().add(1))
        }
    }

    /// Internal helper
    fn set_discriminant(&mut self, discriminant: discriminant_SadPayloadfulTag) {
        let discriminant_ptr: *mut discriminant_SadPayloadfulTag =
            (self as *mut SadPayloadfulTag).cast();

        unsafe {
            *(discriminant_ptr.add(1)) = discriminant;
        }
    }
}

#[derive(Copy)]
#[repr(C)]
pub struct SadPayloadfulTag {
    payload: union_SadPayloadfulTag,
    discriminant: discriminant_SadPayloadfulTag,
}

impl Clone for SadPayloadfulTag {
    fn clone(&self) -> Self {
        use discriminant_SadPayloadfulTag::*;

        let payload = unsafe {
            match self.discriminant {
                Bar => union_SadPayloadfulTag {
                    Bar: self.payload.Bar.clone(),
                },
                Baz => union_SadPayloadfulTag {
                    Baz: self.payload.Baz.clone(),
                },
                Foo => union_SadPayloadfulTag {
                    Foo: self.payload.Foo.clone(),
                },
            }
        };

        Self {
            discriminant: self.discriminant,
            payload,
        }
    }
}

impl core::fmt::Debug for SadPayloadfulTag {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        use discriminant_SadPayloadfulTag::*;

        unsafe {
            match self.discriminant {
                Bar => {
                    let field: &() = &self.payload.Bar;
                    f.debug_tuple("SadPayloadfulTag::Bar").field(field).finish()
                }
                Baz => {
                    let field: &() = &self.payload.Baz;
                    f.debug_tuple("SadPayloadfulTag::Baz").field(field).finish()
                }
                Foo => {
                    let field: &u8 = &self.payload.Foo;
                    f.debug_tuple("SadPayloadfulTag::Foo").field(field).finish()
                }
            }
        }
    }
}

impl Eq for SadPayloadfulTag {}

impl PartialEq for SadPayloadfulTag {
    fn eq(&self, other: &Self) -> bool {
        use discriminant_SadPayloadfulTag::*;

        if self.discriminant != other.discriminant {
            return false;
        }

        unsafe {
            match self.discriminant {
                Bar => self.payload.Bar == other.payload.Bar,
                Baz => self.payload.Baz == other.payload.Baz,
                Foo => self.payload.Foo == other.payload.Foo,
            }
        }
    }
}

impl Ord for SadPayloadfulTag {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.partial_cmp(other).unwrap()
    }
}

impl PartialOrd for SadPayloadfulTag {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        use discriminant_SadPayloadfulTag::*;

        use std::cmp::Ordering::*;

        match self.discriminant.cmp(&other.discriminant) {
            Less => Option::Some(Less),
            Greater => Option::Some(Greater),
            Equal => unsafe {
                match self.discriminant {
                    Bar => self.payload.Bar.partial_cmp(&other.payload.Bar),
                    Baz => self.payload.Baz.partial_cmp(&other.payload.Baz),
                    Foo => self.payload.Foo.partial_cmp(&other.payload.Foo),
                }
            },
        }
    }
}

impl core::hash::Hash for SadPayloadfulTag {
    fn hash<H: core::hash::Hasher>(&self, state: &mut H) {
        use discriminant_SadPayloadfulTag::*;

        unsafe {
            match self.discriminant {
                Bar => self.payload.Bar.hash(state),
                Baz => self.payload.Baz.hash(state),
                Foo => self.payload.Foo.hash(state),
            }
        }
    }
}

impl SadPayloadfulTag {
    pub fn is_Bar(&self) -> bool {
        matches!(self.discriminant, discriminant_SadPayloadfulTag::Bar)
    }

    pub fn is_Baz(&self) -> bool {
        matches!(self.discriminant, discriminant_SadPayloadfulTag::Baz)
    }

    pub fn unwrap_Foo(mut self) -> u8 {
        debug_assert_eq!(self.discriminant, discriminant_SadPayloadfulTag::Foo);
        unsafe { self.payload.Foo }
    }

    pub fn borrow_Foo(&self) -> u8 {
        debug_assert_eq!(self.discriminant, discriminant_SadPayloadfulTag::Foo);
        unsafe { self.payload.Foo }
    }

    pub fn borrow_mut_Foo(&mut self) -> &mut u8 {
        debug_assert_eq!(self.discriminant, discriminant_SadPayloadfulTag::Foo);
        unsafe { &mut self.payload.Foo }
    }

    pub fn is_Foo(&self) -> bool {
        matches!(self.discriminant, discriminant_SadPayloadfulTag::Foo)
    }
}

impl SadPayloadfulTag {
    pub fn Bar() -> Self {
        Self {
            discriminant: discriminant_SadPayloadfulTag::Bar,
            payload: union_SadPayloadfulTag { Bar: () },
        }
    }

    pub fn Baz() -> Self {
        Self {
            discriminant: discriminant_SadPayloadfulTag::Baz,
            payload: union_SadPayloadfulTag { Baz: () },
        }
    }

    pub fn Foo(payload: u8) -> Self {
        Self {
            discriminant: discriminant_SadPayloadfulTag::Foo,
            payload: union_SadPayloadfulTag { Foo: payload },
        }
    }
}

roc_refcounted_noop_impl!(SadPayloadfulTag);

#[derive(Clone, Copy, Default, Debug, PartialEq, PartialOrd, Eq, Ord, Hash)]
#[repr(C)]
pub struct Fluff {
    pub a: u64,
    pub b: u64,
    pub c: u64,
    pub d: u64,
}

roc_refcounted_noop_impl!(Fluff);

#[derive(Clone, Copy, Default, Debug, PartialEq, PartialOrd, Eq, Ord, Hash)]
#[repr(C)]
pub struct SadPayloadfulTagFluffed_Foo {
    pub f1: Fluff,
    pub f0: u8,
}

roc_refcounted_noop_impl!(SadPayloadfulTagFluffed_Foo);

#[derive(Clone, Copy, PartialEq, PartialOrd, Eq, Ord, Hash)]
#[repr(u8)]
pub enum discriminant_SadPayloadfulTagFluffed {
    Bar = 0,
    Baz = 1,
    Foo = 2,
}

impl core::fmt::Debug for discriminant_SadPayloadfulTagFluffed {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Bar => f.write_str("discriminant_SadPayloadfulTagFluffed::Bar"),
            Self::Baz => f.write_str("discriminant_SadPayloadfulTagFluffed::Baz"),
            Self::Foo => f.write_str("discriminant_SadPayloadfulTagFluffed::Foo"),
        }
    }
}

roc_refcounted_noop_impl!(discriminant_SadPayloadfulTagFluffed);

#[derive(Clone, Copy)]
#[repr(C, align(8))]
pub union union_SadPayloadfulTagFluffed {
    Bar: (),
    Baz: (),
    Foo: SadPayloadfulTagFluffed_Foo,
}

// TODO(@roc-lang): See https://github.com/roc-lang/roc/issues/6012
// const _SIZE_CHECK_union_SadPayloadfulTagFluffed: () = assert!(core::mem::size_of::<union_SadPayloadfulTagFluffed>() == 48);
const _ALIGN_CHECK_union_SadPayloadfulTagFluffed: () =
    assert!(core::mem::align_of::<union_SadPayloadfulTagFluffed>() == 8);

const _SIZE_CHECK_SadPayloadfulTagFluffed: () =
    assert!(core::mem::size_of::<SadPayloadfulTagFluffed>() == 48);
const _ALIGN_CHECK_SadPayloadfulTagFluffed: () =
    assert!(core::mem::align_of::<SadPayloadfulTagFluffed>() == 8);

impl SadPayloadfulTagFluffed {
    /// Returns which variant this tag union holds. Note that this never includes a payload!
    pub fn discriminant(&self) -> discriminant_SadPayloadfulTagFluffed {
        unsafe {
            let bytes = core::mem::transmute::<&Self, &[u8; core::mem::size_of::<Self>()]>(self);

            core::mem::transmute::<u8, discriminant_SadPayloadfulTagFluffed>(
                *bytes.as_ptr().add(40),
            )
        }
    }

    /// Internal helper
    fn set_discriminant(&mut self, discriminant: discriminant_SadPayloadfulTagFluffed) {
        let discriminant_ptr: *mut discriminant_SadPayloadfulTagFluffed =
            (self as *mut SadPayloadfulTagFluffed).cast();

        unsafe {
            *(discriminant_ptr.add(40)) = discriminant;
        }
    }
}

#[derive(Copy)]
#[repr(C)]
pub struct SadPayloadfulTagFluffed {
    payload: union_SadPayloadfulTagFluffed,
    discriminant: discriminant_SadPayloadfulTagFluffed,
}

impl Clone for SadPayloadfulTagFluffed {
    fn clone(&self) -> Self {
        use discriminant_SadPayloadfulTagFluffed::*;

        let payload = unsafe {
            match self.discriminant {
                Bar => union_SadPayloadfulTagFluffed {
                    Bar: self.payload.Bar.clone(),
                },
                Baz => union_SadPayloadfulTagFluffed {
                    Baz: self.payload.Baz.clone(),
                },
                Foo => union_SadPayloadfulTagFluffed {
                    Foo: self.payload.Foo.clone(),
                },
            }
        };

        Self {
            discriminant: self.discriminant,
            payload,
        }
    }
}

impl core::fmt::Debug for SadPayloadfulTagFluffed {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        use discriminant_SadPayloadfulTagFluffed::*;

        unsafe {
            match self.discriminant {
                Bar => {
                    let field: &() = &self.payload.Bar;
                    f.debug_tuple("SadPayloadfulTagFluffed::Bar")
                        .field(field)
                        .finish()
                }
                Baz => {
                    let field: &() = &self.payload.Baz;
                    f.debug_tuple("SadPayloadfulTagFluffed::Baz")
                        .field(field)
                        .finish()
                }
                Foo => {
                    let field: &SadPayloadfulTagFluffed_Foo = &self.payload.Foo;
                    f.debug_tuple("SadPayloadfulTagFluffed::Foo")
                        .field(field)
                        .finish()
                }
            }
        }
    }
}

impl Eq for SadPayloadfulTagFluffed {}

impl PartialEq for SadPayloadfulTagFluffed {
    fn eq(&self, other: &Self) -> bool {
        use discriminant_SadPayloadfulTagFluffed::*;

        if self.discriminant != other.discriminant {
            return false;
        }

        unsafe {
            match self.discriminant {
                Bar => self.payload.Bar == other.payload.Bar,
                Baz => self.payload.Baz == other.payload.Baz,
                Foo => self.payload.Foo == other.payload.Foo,
            }
        }
    }
}

impl Ord for SadPayloadfulTagFluffed {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.partial_cmp(other).unwrap()
    }
}

impl PartialOrd for SadPayloadfulTagFluffed {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        use discriminant_SadPayloadfulTagFluffed::*;

        use std::cmp::Ordering::*;

        match self.discriminant.cmp(&other.discriminant) {
            Less => Option::Some(Less),
            Greater => Option::Some(Greater),
            Equal => unsafe {
                match self.discriminant {
                    Bar => self.payload.Bar.partial_cmp(&other.payload.Bar),
                    Baz => self.payload.Baz.partial_cmp(&other.payload.Baz),
                    Foo => self.payload.Foo.partial_cmp(&other.payload.Foo),
                }
            },
        }
    }
}

impl core::hash::Hash for SadPayloadfulTagFluffed {
    fn hash<H: core::hash::Hasher>(&self, state: &mut H) {
        use discriminant_SadPayloadfulTagFluffed::*;

        unsafe {
            match self.discriminant {
                Bar => self.payload.Bar.hash(state),
                Baz => self.payload.Baz.hash(state),
                Foo => self.payload.Foo.hash(state),
            }
        }
    }
}

impl SadPayloadfulTagFluffed {
    pub fn is_Bar(&self) -> bool {
        matches!(self.discriminant, discriminant_SadPayloadfulTagFluffed::Bar)
    }

    pub fn is_Baz(&self) -> bool {
        matches!(self.discriminant, discriminant_SadPayloadfulTagFluffed::Baz)
    }

    pub fn unwrap_Foo(mut self) -> SadPayloadfulTagFluffed_Foo {
        debug_assert_eq!(self.discriminant, discriminant_SadPayloadfulTagFluffed::Foo);
        unsafe { self.payload.Foo }
    }

    pub fn borrow_Foo(&self) -> SadPayloadfulTagFluffed_Foo {
        debug_assert_eq!(self.discriminant, discriminant_SadPayloadfulTagFluffed::Foo);
        unsafe { self.payload.Foo }
    }

    pub fn borrow_mut_Foo(&mut self) -> &mut SadPayloadfulTagFluffed_Foo {
        debug_assert_eq!(self.discriminant, discriminant_SadPayloadfulTagFluffed::Foo);
        unsafe { &mut self.payload.Foo }
    }

    pub fn is_Foo(&self) -> bool {
        matches!(self.discriminant, discriminant_SadPayloadfulTagFluffed::Foo)
    }
}

impl SadPayloadfulTagFluffed {
    pub fn Bar() -> Self {
        Self {
            discriminant: discriminant_SadPayloadfulTagFluffed::Bar,
            payload: union_SadPayloadfulTagFluffed { Bar: () },
        }
    }

    pub fn Baz() -> Self {
        Self {
            discriminant: discriminant_SadPayloadfulTagFluffed::Baz,
            payload: union_SadPayloadfulTagFluffed { Baz: () },
        }
    }

    pub fn Foo(payload: SadPayloadfulTagFluffed_Foo) -> Self {
        Self {
            discriminant: discriminant_SadPayloadfulTagFluffed::Foo,
            payload: union_SadPayloadfulTagFluffed { Foo: payload },
        }
    }
}

roc_refcounted_noop_impl!(SadPayloadfulTagFluffed);

#[derive(Clone, Copy, PartialEq, PartialOrd, Eq, Ord, Hash)]
#[repr(u8)]
pub enum discriminant_ThingsToGlue {
    A = 0,
    B = 1,
    C = 2,
}

impl core::fmt::Debug for discriminant_ThingsToGlue {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::A => f.write_str("discriminant_ThingsToGlue::A"),
            Self::B => f.write_str("discriminant_ThingsToGlue::B"),
            Self::C => f.write_str("discriminant_ThingsToGlue::C"),
        }
    }
}

roc_refcounted_noop_impl!(discriminant_ThingsToGlue);

#[repr(C, align(8))]
pub union union_ThingsToGlue {
    A: HappyPayloadlessTag,
    B: SadPayloadfulTag,
    C: SadPayloadfulTagFluffed,
}

// TODO(@roc-lang): See https://github.com/roc-lang/roc/issues/6012
// const _SIZE_CHECK_union_ThingsToGlue: () = assert!(core::mem::size_of::<union_ThingsToGlue>() == 48);
const _ALIGN_CHECK_union_ThingsToGlue: () =
    assert!(core::mem::align_of::<union_ThingsToGlue>() == 8);

const _SIZE_CHECK_ThingsToGlue: () = assert!(core::mem::size_of::<ThingsToGlue>() == 56);
const _ALIGN_CHECK_ThingsToGlue: () = assert!(core::mem::align_of::<ThingsToGlue>() == 8);

impl ThingsToGlue {
    /// Returns which variant this tag union holds. Note that this never includes a payload!
    pub fn discriminant(&self) -> discriminant_ThingsToGlue {
        unsafe {
            let bytes = core::mem::transmute::<&Self, &[u8; core::mem::size_of::<Self>()]>(self);

            core::mem::transmute::<u8, discriminant_ThingsToGlue>(*bytes.as_ptr().add(48))
        }
    }

    /// Internal helper
    fn set_discriminant(&mut self, discriminant: discriminant_ThingsToGlue) {
        let discriminant_ptr: *mut discriminant_ThingsToGlue = (self as *mut ThingsToGlue).cast();

        unsafe {
            *(discriminant_ptr.add(48)) = discriminant;
        }
    }
}

#[repr(C)]
pub struct ThingsToGlue {
    payload: union_ThingsToGlue,
    discriminant: discriminant_ThingsToGlue,
}

impl Clone for ThingsToGlue {
    fn clone(&self) -> Self {
        use discriminant_ThingsToGlue::*;

        let payload = unsafe {
            match self.discriminant {
                A => union_ThingsToGlue {
                    A: self.payload.A.clone(),
                },
                B => union_ThingsToGlue {
                    B: self.payload.B.clone(),
                },
                C => union_ThingsToGlue {
                    C: self.payload.C.clone(),
                },
            }
        };

        Self {
            discriminant: self.discriminant,
            payload,
        }
    }
}

impl core::fmt::Debug for ThingsToGlue {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        use discriminant_ThingsToGlue::*;

        unsafe {
            match self.discriminant {
                A => {
                    let field: &HappyPayloadlessTag = &self.payload.A;
                    f.debug_tuple("ThingsToGlue::A").field(field).finish()
                }
                B => {
                    let field: &SadPayloadfulTag = &self.payload.B;
                    f.debug_tuple("ThingsToGlue::B").field(field).finish()
                }
                C => {
                    let field: &SadPayloadfulTagFluffed = &self.payload.C;
                    f.debug_tuple("ThingsToGlue::C").field(field).finish()
                }
            }
        }
    }
}

impl Eq for ThingsToGlue {}

impl PartialEq for ThingsToGlue {
    fn eq(&self, other: &Self) -> bool {
        use discriminant_ThingsToGlue::*;

        if self.discriminant != other.discriminant {
            return false;
        }

        unsafe {
            match self.discriminant {
                A => self.payload.A == other.payload.A,
                B => self.payload.B == other.payload.B,
                C => self.payload.C == other.payload.C,
            }
        }
    }
}

impl Ord for ThingsToGlue {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.partial_cmp(other).unwrap()
    }
}

impl PartialOrd for ThingsToGlue {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        use discriminant_ThingsToGlue::*;

        use std::cmp::Ordering::*;

        match self.discriminant.cmp(&other.discriminant) {
            Less => Option::Some(Less),
            Greater => Option::Some(Greater),
            Equal => unsafe {
                match self.discriminant {
                    A => self.payload.A.partial_cmp(&other.payload.A),
                    B => self.payload.B.partial_cmp(&other.payload.B),
                    C => self.payload.C.partial_cmp(&other.payload.C),
                }
            },
        }
    }
}

impl core::hash::Hash for ThingsToGlue {
    fn hash<H: core::hash::Hasher>(&self, state: &mut H) {
        use discriminant_ThingsToGlue::*;

        unsafe {
            match self.discriminant {
                A => self.payload.A.hash(state),
                B => self.payload.B.hash(state),
                C => self.payload.C.hash(state),
            }
        }
    }
}

impl ThingsToGlue {
    pub fn unwrap_A(mut self) -> HappyPayloadlessTag {
        debug_assert_eq!(self.discriminant, discriminant_ThingsToGlue::A);
        unsafe { self.payload.A }
    }

    pub fn borrow_A(&self) -> HappyPayloadlessTag {
        debug_assert_eq!(self.discriminant, discriminant_ThingsToGlue::A);
        unsafe { self.payload.A }
    }

    pub fn borrow_mut_A(&mut self) -> &mut HappyPayloadlessTag {
        debug_assert_eq!(self.discriminant, discriminant_ThingsToGlue::A);
        unsafe { &mut self.payload.A }
    }

    pub fn is_A(&self) -> bool {
        matches!(self.discriminant, discriminant_ThingsToGlue::A)
    }

    pub fn unwrap_B(mut self) -> SadPayloadfulTag {
        debug_assert_eq!(self.discriminant, discriminant_ThingsToGlue::B);
        unsafe { self.payload.B }
    }

    pub fn borrow_B(&self) -> SadPayloadfulTag {
        debug_assert_eq!(self.discriminant, discriminant_ThingsToGlue::B);
        unsafe { self.payload.B }
    }

    pub fn borrow_mut_B(&mut self) -> &mut SadPayloadfulTag {
        debug_assert_eq!(self.discriminant, discriminant_ThingsToGlue::B);
        unsafe { &mut self.payload.B }
    }

    pub fn is_B(&self) -> bool {
        matches!(self.discriminant, discriminant_ThingsToGlue::B)
    }

    pub fn unwrap_C(mut self) -> SadPayloadfulTagFluffed {
        debug_assert_eq!(self.discriminant, discriminant_ThingsToGlue::C);
        unsafe { self.payload.C }
    }

    pub fn borrow_C(&self) -> SadPayloadfulTagFluffed {
        debug_assert_eq!(self.discriminant, discriminant_ThingsToGlue::C);
        unsafe { self.payload.C }
    }

    pub fn borrow_mut_C(&mut self) -> &mut SadPayloadfulTagFluffed {
        debug_assert_eq!(self.discriminant, discriminant_ThingsToGlue::C);
        unsafe { &mut self.payload.C }
    }

    pub fn is_C(&self) -> bool {
        matches!(self.discriminant, discriminant_ThingsToGlue::C)
    }
}

impl ThingsToGlue {
    pub fn A(payload: HappyPayloadlessTag) -> Self {
        Self {
            discriminant: discriminant_ThingsToGlue::A,
            payload: union_ThingsToGlue { A: payload },
        }
    }

    pub fn B(payload: SadPayloadfulTag) -> Self {
        Self {
            discriminant: discriminant_ThingsToGlue::B,
            payload: union_ThingsToGlue { B: payload },
        }
    }

    pub fn C(payload: SadPayloadfulTagFluffed) -> Self {
        Self {
            discriminant: discriminant_ThingsToGlue::C,
            payload: union_ThingsToGlue { C: payload },
        }
    }
}

roc_refcounted_noop_impl!(ThingsToGlue);

pub fn mainForHost() -> ThingsToGlue {
    extern "C" {
        fn roc__mainForHost_1_exposed_generic(_: *mut ThingsToGlue);
    }

    let mut ret = core::mem::MaybeUninit::uninit();

    unsafe {
        roc__mainForHost_1_exposed_generic(ret.as_mut_ptr());

        ret.assume_init()
    }
}
