[toolchain]
# How to update version:
#  - update `channel = "RUST_VERSION"`
#  - to update the nightly version:
#     - Find the latest nightly release that matches RUST_VERSION here: https://github.com/oxalica/rust-overlay/tree/master/manifests/nightly/2023
#     - update `channel = "nightly-OLD_DATE"` below

channel = "1.74.1" # check ^^^ when changing this
# 
# channel = "nightly-2023-10-01" # 1.74.0 nightly to be able to use unstable features
