on: 
    pull_request:
    workflow_dispatch:

# this cancels workflows currently in progress if you start a new one
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-and-test:
        strategy:
            fail-fast: false
            matrix:
              # macos-11 uses x86-64 machine, macos-14 uses aarch64  
              os: [ macos-11, macos-14, ubuntu-22.04 ]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            # install nix
            - uses: cachix/install-nix-action@v23
              with:
                nix_path: nixpkgs=channel:nixos-unstable

            - uses: cachix/cachix-action@v12
              with:
                  name: enigmaticsunrise
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

            - name: print architecture
              run: uname -m

            - name: Run all tests
              run: nix develop -c sh -c 'export ROC=roc && export EXAMPLES_DIR=./examples/ && ./ci/all_tests.sh'
            
            - name: Run all tests and capture output to check for crash later
              run: nix develop -c sh -c 'export ROC=roc && export EXAMPLES_DIR=./examples/ && ./ci/all_tests.sh 2>&1 | tee all_tests_output.log'

            # Workaround for https://github.com/roc-lang/roc/issues/6688
            - name: Check if crash occurred
              run: grep -zqv "crashed" all_tests_output.log
    
    
